TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Flowpack.SearchPlugin': TRUE

  TypoScript:
    defaultContext:
      Flowpack.SearchPlugin.Array: 'Flowpack\SearchPlugin\EelHelper\SearchArrayHelper'
